[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "osgscipy"
version = "0.0.1"
description = "A package"
readme = "README.md"
requires-python = ">=3.8"